name: build

on:
  repository_dispatch:
    types: [build]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0

      - name: Check Node.js version
        run: node -v

      - name: Install dependencies using pnpm i
        run: pnpm i

      - name: Build express
        run: pnpm build
